### ISSUE TITLE
whats encryption algorithm?

### ISSUE THREAD

**Issue by MahdiPishguy** [hummatli/SimpleEncryptionLib#2]
encrypting algorithm text is md5 or hash or AES ?

**Comment by hummatli** [comment]
Hi, @MahdiPishguy .

I haven't used special algorithm here, 

There is a problem [(Look here)](https://stackoverflow.com/questions/32935783/java-different-results-when-decoding-base64-string-with-java-util-base64-vs-and) with Base64 class in Android and (Oracle)Java SDK. They have both this class but has some little differences and different packages. 
#### Packages
* In Oracle's java - java.util.Base64 
* In Android - android.util.Base64

I have taken Oracle's version and has created this lib. Buy the help of it you can use Oracle's Base64 in Android application.  It eases your encryption and decryption process with the same function in Android application and in pure Java application.

Regards, Sattar Hummatli

**Comment by MahdiPishguy** [comment]
@hummatli i understand, thanks to share this library arkadash!!

**Comment by hummatli** [comment]
@MahdiPishguy, Thanks for your attention. Are you turk, Qardash?

**Comment by MahdiPishguy** [comment]
@hummatli yes i but i live in iran, i speaking Azeri ;)

**Comment by hummatli** [comment]
Mən də Azəriyəm. Azərbaycanda yaşayıram. Bu mənim [facebook](https://facebook.com/hummatli) ünvanımdır. İstəsən dostluq göndər.

**Comment by MahdiPishguy** [comment]
@hummatli facebook da sənin üçun message gondəardim
